version: '3.7'
services: 
  web: 
    image: my-django-app
    ports:
      - "8000:8000"
    environment: 
        - DB_HOST=db
        - DB_NAME=user
    depends_on: 
        - db
    deploy:
      resources:
        limits:          
          memory: 40M
          cpus: '0.2'
        reservations:          
          memory: 20M
  db:
    image: mongo
    restart: always
    command: mongod --quiet --logpath /dev/null 
    ports:
      - "27017:27017" 
    deploy:
      resources:
        limits:          
          memory: 50M
          cpus: '0.09'
        reservations:          
          memory: 20M
    volumes:
          - F:/Temp/mongo_docker_data:/data/db
  
volumes:
   postgres_data: 